#!/bin/bash

function sort_vscode_settings {

    find src/bash/profiles/*/Library/"Application Support"/Code/*/settings.json -type f -print0 | 
        while IFS= read -r -d '' path; do 
            node "src/node/sort-vscode-settings.js" "$path";
        done

}

function set_git_author {

    git config --global user.name "$MY_AUTHOR_NAME"
    git config --global user.email "$MY_AUTHOR_EMAIL"

}

function harmonise {
    sort_vscode_settings
    set_git_author
}

harmonise
